sqlite: &sqlite
  adapter: sqlite3
  pool: 5
  timeout: 5000

mysql: &mysql
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: "<%= ENV["C4SA_MYSQL_HOST"] %>"
  database: "<%= ENV["C4SA_MYSQL_DB"] %>"
  username: "<%= ENV["C4SA_MYSQL_USER"] %>"
  password: "<%= ENV["C4SA_MYSQL_PASSWORD"] %>"

development:
  <<: *sqlite
  database: db/development.sqlite3

production:
  <<: *mysql
  
#development:
#  <<: *mysql
