mysql: &mysql
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: "<%= ENV["C4SA_MYSQL_HOST"] %>"
  database: "<%= ENV["C4SA_MYSQL_DB"] %>"
  username: "<%= ENV["C4SA_MYSQL_USER"] %>"
  password: "<%= ENV["C4SA_MYSQL_PASSWORD"] %>"

development:
  <<: *mysql

production:
  <<: *mysql
